# ------------------------------------------------------------
# English language
# ------------------------------------------------------------
[en]
languageName = "English|英文"
languageCode = "en-us"
weight = 1

# ------------------------------------------------------------
# Chinese language
# ------------------------------------------------------------
[zh]
languageName = "Chinese|中文"
languageCode = "zh-cn"
weight = 2
