############# French navigation ##############

[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
name = "问答"
url = "faq/"
weight = 2

[[main]]
name = "联系我们"
url = "contact/"
weight = 3

# Dropdown menu
[[main]]
weight = 4
name = "文档"
hasChildren = true

  [[main]]
  parent = "文档"
  name = "安装"
  url = "installation/"
  weight = 1

  [[main]]
  parent = "文档"
  name = "订单价格"
  url = "billing-pricing/"
  weight = 2

  [[main]]
  parent = "文档"
  name = "NFC"
  url = "mobile/"
  weight = 3
